Replacing COMMAND with CLAUSE
datacarpentry/sql-ecology-lesson pull request #347
Opened 2022-11-28 18:43 UTC by singlarohit

I am proposing to change the term "command" with "clause" as they are used interchangeably throughout the episodes  2, 3 and 4 of the lesson. I believe that only one term (preferably "clause") must be used to avoid any confusion to the readers. 

Because SQL comes from the field of Computer science, I believe that use of "clause" is more appropriate in this context. I strongly feel that the above occurrences of "command" must be changed with "clause" to maintain consistency in the lesson.

2022-11-30 03:28 UTC, jd-foster requested changes
I've tried to use the words that best fit in the context.

2022-11-30 03:28 UTC, jd-foster commented on _episodes/01-sql-basic-queries.md
> +Sometimes you don't want to see all the results, you just want to get a sense of what's being returned. In that case, you can use the `LIMIT` clause. In particular, you would want to do this if you w
Agreed, but change "the" to "a" : "a `LIMIT` clause`

2022-11-30 03:28 UTC, jd-foster commented on _episodes/02-sql-aggregation.md
> +Here the `COUNT` clause includes all five records (even those with NULL
Here, "function" seems the best choice

2022-11-30 03:28 UTC, jd-foster commented on _episodes/02-sql-aggregation.md
> +our strategy *will* work if we modify the `COUNT` clause slightly:
Also "function", but "clause" works if you feel strongly about it.

2022-11-30 03:28 UTC, jd-foster commented on _episodes/03-sql-joins.md
> +- "Use the `JOIN` clause to combine data from two tables---the `ON` or `USING` keywords specify which columns link the tables."
This one should be either "keyword" or change to "a `JOIN` clause".

2022-11-30 03:28 UTC, jd-foster commented on _episodes/03-sql-joins.md
> +- "Regular `JOIN` returns only matching rows. Other join clauses provide different behavior, e.g., `LEFT JOIN` retains all rows of the table on the left side of the clause."
Yes.

2022-11-30 03:28 UTC, jd-foster commented on _episodes/03-sql-joins.md
> +To combine data from two tables we use the SQL `JOIN` clause, which comes after
"a SQL `JOIN` clause"

2022-11-30 03:28 UTC, jd-foster commented on _episodes/03-sql-joins.md
> +The `JOIN` clause on its own will result in a cross product, where each row in
"A `JOIN` clause"

2022-11-30 03:28 UTC, jd-foster commented on _episodes/03-sql-joins.md
> +The JOIN clause combined with ON is used to combine fields from separate tables.
"keyword"

2022-11-30 03:28 UTC, jd-foster commented on _episodes/03-sql-joins.md
> +The output of the `JOIN` clause will have columns from the first table plus the
"The output from using the `JOIN` clause"

2022-11-30 03:28 UTC, jd-foster commented on _episodes/03-sql-joins.md
> +columns from the second table. For the above clause, the output will be a table
"statement"

2022-11-30 03:28 UTC, jd-foster commented on _episodes/03-sql-joins.md
> +In fact the `JOIN` clause is simply shorthand for `INNER JOIN` and the two
"keyword"

2022-11-30 03:28 UTC, jd-foster commented on _episodes/03-sql-joins.md
> +table by using the clause `LEFT OUTER JOIN`, or `LEFT JOIN` for short.
"by using a `LEFT OUTER JOIN` clause"

2022-12-04 15:02 UTC, singlarohit commented
I just committed the aforementioned changes (Commit # 063b8e9) suggested by you.

2022-12-04 23:56 UTC, merged

2022-12-04 23:56 UTC, jd-foster commented
Thanks, very nice.