Update CONTRIBUTING.md to address #356
datacarpentry/sql-ecology-lesson pull request #358
Opened 2023-06-06 05:37 UTC by jd-foster

See issue #356:
>  1. the How to Contribute to an Open Source Project on GitHub link leads to a 404 and should be updated to link to https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github
>  1. the [repo] link reference currently points to a placeholder URL (https://example.com/FIXME) and should be updated to point to the source repository for the lesson (i.e. this GitHub repository).

2023-06-06 15:46 UTC, adamancer requested changes
The trailing slash breaks the three issues links, other than that this looks good. Thanks!

2023-06-06 15:46 UTC, adamancer commented on CONTRIBUTING.md
> +[dc-issues]: https://github.com/issues?q=user%3Adatacarpentry/
The trailing slash breaks this link

2023-06-06 15:46 UTC, adamancer commented on CONTRIBUTING.md
> +[lc-issues]: https://github.com/issues?q=user%3ALibraryCarpentry/
And this one

2023-06-06 15:46 UTC, adamancer commented on CONTRIBUTING.md
> +[swc-issues]: https://github.com/issues?q=user%3Aswcarpentry/
And this one

2023-06-07 03:33 UTC, jd-foster commented
🤦 
@adamancer Thanks for picking this up. Not sure why I was thinking I needed to add them to everything.

2023-06-09 22:28 UTC, merged